SELECT H.HACKER_ID, H.NAME, SUM(MAX_SCORE.SCORE) AS CNT
FROM HACKERS H
JOIN 
--WHEN MULTIPLE CHALLENGE ID'S ARE THE SAME TAKE THE HIGHEST SCORE
            (SELECT HACKER_ID, MAX(SCORE) AS SCORE 
            FROM SUBMISSIONS 
            GROUP BY CHALLENGE_ID, HACKER_ID) MAX_SCORE
ON H.HACKER_ID = MAX_SCORE.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING CNT > 0
ORDER BY CNT DESC, HACKER_ID